general/core/urls.py
from django.urls import path

from . import views


app_name = "core"

urlpatterns = [path("", views.HomeView.as_view(), name="home")]

general/gmanager/urls.py
from core.mixins import OpenView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.utils.translation import gettext_lazy as _


module_urls = i18n_patterns(
    path("", include("core.urls", namespace="core")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.backends.simple.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("employees/", include("employees.urls", namespace="employees")),
    prefix_default_language=False,
)

plugin_urls = [
    path("tinymce/", include("tinymce.urls")),
    path("translate/", include("rosetta.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml", OpenView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", OpenView.as_view(template_name="robots.txt", content_type="text/plain")),
    path(
        "OneSignalSDKWorker.js", OpenView.as_view(template_name="OneSignalSDKWorker.js", content_type="text/javascript")
    ),
]

urlpatterns = (
    module_urls
    + plugin_urls
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

PROJECT_NAME = settings.APP_SETTINGS.get("site_name")
admin.site.site_header = _("%(project_name)s Administration") % {"project_name": PROJECT_NAME}
admin.site.site_title = _("%(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}
admin.site.index_title = _("Welcome to %(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}

general/user_sessions/urls.py
from django.urls import path
from django.urls import re_path
from user_sessions.views import SessionDeleteOtherView

from .views import SessionDeleteView
from .views import SessionListView


app_name = "user_sessions"
urlpatterns = [
    path("account/sessions/", view=SessionListView.as_view(), name="session_list"),
    path("account/sessions/other/delete/", view=SessionDeleteOtherView.as_view(), name="session_delete_other"),
    re_path(r"^account/sessions/(?P<pk>\w+)/delete/$", view=SessionDeleteView.as_view(), name="session_delete"),
]

general/templates/app/partials/filter.html
{% load i18n crispy_forms_tags %}

<div class="offcanvas offcanvas-end" id="offcanvasFilter" aria-labelledby="offcanvasFilterLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasFilterLabel">Filter Data</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <form action="" method="get">
            <div class="modal-body">
                <div class="row">
                    {% for field in filter.form %}
                    <div class="col-12">
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field|as_crispy_field }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="reset" class="btn btn-white me-auto border">{% translate "Reset" %}</button>
                <a href="javascript:void(0);" class="btn btn-outline-white border" data-bs-dismiss="modal">
                    {% translate "Cancel" %}</a>
                <button type="submit" class="btn btn-primary">{% translate "Apply" %}</button>
            </div>
        </form>
    </div>
</div>

general/templates/app/partials/head.html
{% load static compress %}

<meta content="{{author}}" name="author">
<meta name="keywords" content="" />

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-config" content="{% static 'static/app/images/favicons/browserconfig.xml' %}?v=1.3">
<meta name="theme-color" content="#ffffff">


{% compress css %}
<link href="{% static 'app/plugins/bootstrap/css/bootstrap.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/style.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/plugins.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/boxed.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/dark.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/skin-modes.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/transparent-style.css' %}?v=1.3" rel="stylesheet">
<link href="{% static 'app/css/animated.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/plugins/jqueryui.css' %}?v=1.3" rel="stylesheet" />
{% endcompress %}

{% block extra_css %}{% endblock %}

<link href="{% static 'app/css/icons.css' %}?v=1.3" rel="stylesheet" />
<link href="{% static 'app/css/custom.css' %}?v=1.3" rel="stylesheet" />
<script src="{% static 'app/plugins/jquery/jquery.min.js' %}?v=1.3"></script>

general/templates/app/partials/header.html
{% load static extras humanize %}
<!--app header-->
<div class="app-header header sticky">
    <div class="container-fluid main-container">
        <div class="d-flex align-items-center">

            <a class="header-brand" href="/">
                <img src="{{app_settings.logo}}" class="header-brand-img desktop-lgo" alt="{{app_settings.site_name}}">
                <img src="{{app_settings.logo}}" class="header-brand-img dark-logo" alt="{{app_settings.site_name}}">
                <img src="{{app_settings.logo_mini}}" class="header-brand-img mobile-logo mt-0 ml-1"
                    alt="{{app_settings.site_name}}">
                <img src="{{app_settings.logo_mini}}" class="header-brand-img darkmobile-logo" alt="{{app_settings.site_name}}">
            </a>

            <div class="app-sidebar__toggle" data-bs-toggle="sidebar">
                <a class="open-toggle" href="javascript:void(0);">
                    <i class="feather feather-menu"></i>
                </a>
                <a class="close-toggle" href="javascript:void(0);">
                    <i class="feather feather-x"></i>
                </a>
            </div>

            <div class="mt-0">
                <a class="nav-link icon" href="javascript:void(0)" onclick="history.back()">
                    <i class="feather feather-chevron-left header-icon"></i>
                </a>
            </div>


            <div class="mt-0">
                <form class="form-inline" method="get">
                    <div class="search-element">
                        <input type="search" id="global_search_bar" class="form-control header-search"
                            placeholder="Search or jump to ..." aria-label="Search" tabindex="1">
                        <button class="btn btn-primary-color py-1" type="button">
                            <i class="feather feather-search"></i>
                        </button>
                    </div>
                </form>
            </div><!-- SEARCH -->

            <div class="d-flex order-lg-2 my-auto ms-auto">
                <button class="navbar-toggler nav-link icon navresponsive-toggler vertical-icon ms-auto" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent-4"
                    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fe fe-more-vertical header-icons navbar-toggler-icon"></i>
                </button>
                <div class="mb-0 navbar navbar-expand-lg navbar-nav-right responsive-navbar navbar-dark p-0">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                        <div class="d-flex ms-auto">
                            <div class="dropdown d-flex">
                                <a class="nav-link icon theme-layout nav-link-bg layout-setting">
                                    <span class="dark-layout"><i class="fe fe-moon"></i></span>
                                    <span class="light-layout"><i class="fe fe-sun"></i></span>
                                </a>
                            </div>

                            <div class="dropdown header-fullscreen">
                                <a class="nav-link icon full-screen-link">
                                    <i class="feather feather-maximize fullscreen-button fullscreen header-icons"></i>
                                    <i
                                        class="feather feather-minimize fullscreen-button exit-fullscreen header-icons"></i>
                                </a>
                            </div>

                            <div class="dropdown header-notify">
                                <a class="nav-link icon" data-bs-toggle="sidebar-right"
                                    data-bs-target="#notificationSidebar">
                                    <i class="feather feather-bell header-icon"></i>
                                    <span class="bg-dot"></span>
                                </a>
                            </div>

                            <div class="dropdown profile-dropdown">
                                <a href="javascript:void(0);" class="nav-link p-0 leading-none"
                                    data-bs-toggle="dropdown">
                                    {% if current_employee.photo %}
                                    <img src="{{current_employee.photo.url}}" alt=" " height="40" width="40"
                                        class="avatar avatar-md bradius">
                                    {% else %}
                                    <img src="{{default_user_avatar}}" alt=" " class="avatar avatar-md bradius">
                                    {% endif %}
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow animated">
                                    <div class="p-3 text-center border-bottom">
                                        <a href="#"
                                            class="d-inline-block font-weight-bold mb-2 pb-0 text-center user">{{request.user}}</a>
                                        <p class="text-center user-semi-title mb-0">{{request.user.designation}}</p>
                                    </div>
                                    
                                    <a class="dropdown-item d-flex" href="{% url 'auth_password_change' %}">
                                        <i class="feather feather-edit-2 me-3 fs-16 my-auto"></i>
                                        <div class="mt-1">Change Password</div>
                                    </a>
                                    <a class="dropdown-item d-flex" href="{% url 'user_sessions:session_list' %}">
                                        <i class="feather feather-layers me-3 fs-16 my-auto"></i>
                                        <div class="mt-1">My Sessions</div>
                                    </a>
                                    <a class="dropdown-item d-flex" href="{% url 'auth_logout' %}">
                                        <i class="feather feather-power me-3 fs-16 my-auto"></i>
                                        <div class="mt-1">Sign Out</div>
                                    </a>
                                    <a class="dropdown-item d-flex" href="{% url 'auth_login' %}">
                                        <i class="feather feather-log-in me-3 fs-16 my-auto"></i>
                                        <div class="mt-1">Sign in</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!--/app header-->

general/templates/app/partials/loader.html
{% load static %}
<!---Global-loader-->
<div id="global-loader">
	<img src="{% static 'app/images/svgs/loader.svg' %}" alt="loader">
</div>

general/templates/app/partials/sidebar-right.html
{% load static humanize %}
<div class="sidebar sidebar-right sidebar-animate" id="notificationSidebar">
    <div class="p-relative">
        <div class="card-header border-bottom">
            <h4 class="card-title"><a href="#">Notifications</a> </h4>
            <div class="card-options">
                <a href="javascript:void(0);" class="btn btn-sm btn-icon btn-light  text-primary"
                    data-bs-toggle="sidebar-right" data-bs-target=".sidebar-right"><i class="feather feather-x"></i>
                </a>
            </div>
        </div>
        <div class="">
            {% for notification in notifications %}
            <div class="list-group-item notification_message {% if not notification.is_read %}active{% endif %}">
                <a class="mt-1" href="#">
                    <h6 class="font-weight-semibold fs-16">{{notification.title}} </h6>
                    <small class="text-muted fs-13 ms-auto"><i
                            class="mdi mdi-clock text-muted me-1"></i>{{notification.created | naturaltime }}</small>
                    <p>{{notification.description}}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

general/templates/app/partials/table_actions.html
<a href="{{ record.get_absolute_url }}" class="btn btn-sm btn-light btn-outline-info">OPEN</a>

general/templates/app/partials/task_status_form.html
<form action="{% url 'tasks:task_update_status' record.pk %}" method="GET" class="task_update_form">
    <select name="status" id="status" class="form-control niceselect" style="width:auto">

        {% if record.status == 'todo' %}
        <option value="todo" {% if record.status == 'todo' %} selected {% endif %}>Todo</option>
        <option value="on_going" {% if record.status == 'on_going' %} selected {% endif %}>On Going</option>
        <option value="on_hold" {% if record.status == 'on_hold' %} selected {% endif %}>On Hold</option>
        <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
        <option value="delayed" {% if record.status == 'delayed' %} selected {% endif %}>Delayed</option>
        <option value="cancelled" {% if record.status == 'cancelled' %} selected {% endif %}>Cancelled</option>
        {% endif %}

        {% if record.status == 'on_going' %}
        <option value="on_going" {% if record.status == 'on_going' %} selected {% endif %}>On Going</option>
        <option value="on_hold" {% if record.status == 'on_hold' %} selected {% endif %}>On Hold</option>
        <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
        <option value="delayed" {% if record.status == 'delayed' %} selected {% endif %}>Delayed</option>
        <option value="cancelled" {% if record.status == 'cancelled' %} selected {% endif %}>Cancelled</option>
        {% endif %}

        {% if record.status == 'on_hold' %}
        <option value="on_hold" {% if record.status == 'on_hold' %} selected {% endif %}>On Hold</option>
        <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
        <option value="delayed" {% if record.status == 'delayed' %} selected {% endif %}>Delayed</option>
        <option value="cancelled" {% if record.status == 'cancelled' %} selected {% endif %}>Cancelled</option>
        {% endif %}

        {% if record.status == 'in_review' %}
        <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
        <option value="delayed" {% if record.status == 'delayed' %} selected {% endif %}>Delayed</option>
        {% endif %}

        {% if record.status == 'delayed' %}
        <option value="delayed" {% if record.status == 'delayed' %} selected {% endif %}>Delayed</option>
        {% endif %}

        {% if record.status == 'rework' %}
        <option value="rework" {% if record.status == 'rework' %} selected {% endif %}>Rework</option>
        <option value="in_review" {% if record.status == 'in_review' %} selected {% endif %}>In Review</option>
        {% endif %}

        {% if record.status == 'cancelled' %}
        <option value="cancelled" {% if record.status == 'cancelled' %} selected {% endif %}>Cancelled</option>
        {% endif %}

        {% if record.status == 'done' %}
        <option value="done" {% if record.status == 'done' %} selected {% endif %}>Done</option>
        {% endif %}

        {% if has_authority %}
            {% if record.status == 'rework' or record.status == 'in_review' %}
                <option value="rework" {% if record.status == 'rework' %} selected {% endif %}>Rework</option>
                <option value="done" {% if record.status == 'done' %} selected {% endif %}>Done</option>
            {% endif %}
        {% endif %}

    </select>
</form>

general/templates/app/partials/task_view_modal.html
<button type="button" class="btn btn-gray btn-sm" data-bs-toggle="modal" data-bs-target="#Task_{{record.pk}}">
    View
</button>

<div class="modal fade" id="Task_{{record.pk}}" tabindex="-1" aria-labelledby="Task_{{record.pk}}Label" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="Task_{{record.pk}}Label">{{record.title}}</h5>
            <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="mb-2">{{record.description|linebreaksbr|urlize}}</div>
            <div class="d-flex flex-wrap justify-content-start mt-4">
                <img src="{{record.assigned_to.get_image_url}}" alt="" class="avatar-sm me-1"
                title="{{record.assigned_to}}">
                {% if record.start_from == record.end_before %}
                <span class="my-0 badge bg-warning me-1">{{record.start_from}}</span>
                {% else %}
                <span class="my-0 badge bg-success me-1">{{record.start_from}}</span>
                <span class="my-0 badge bg-danger me-1">{{record.end_before}}</span>
                {% endif %}
            </div>
        </div>
        <div class="modal-footer justify-content-start">
            <div class="footer-content">
                <div class="d-flex flex-wrap justify-content-center mb-3">
                {% if record.remarks %}
                    <button type="button" class="btn btn-sm edit_btn">Edit Remarks</button>
                {% else %}
                    <button type="button" class="btn btn-sm edit_btn">Edit Remarks</button>
                {% endif %}
                {% if record.rework_reason %}
                    <button type="button" class="btn btn-sm edit_btn">Edit Reason</button>
                {% else %}
                    <button type="button" class="btn btn-sm edit_btn">Edit Reason</button>
                {% endif %}
                </div>

                {% if record.remarks %}
                    <p><strong class="d-inline">Remarks: </strong>{{record.remarks|linebreaksbr|urlize}}</p>
                {% endif %}
                {% if record.rework_reason %}
                    <p><strong class="d-inline">Rework Reason: </strong>{{record.rework_reason|linebreaksbr|urlize}}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

general/templates/app/partials/timeout.html
{% load static i18n %}

<div class="modal fade" id="myModal">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content tx-size-sm">
			<div class="modal-body text-center">
				<i class="fe fe-alert-triangle fs-50"></i>
				<h4 class="text-primary fs-20 font-weight-semibold mt-2">Session Timeout</h4>
				<progress id="custom-bar" class="custom-progress mb-4 wd-70p mt-3" max="100" value="0">0%</progress>
				<p class="mb-4 mx-4">You're being timed out due to inactivity. Please choose to stay signed in or to
					logoff. Otherwise, you will logged off automatically..</p>
				<a class="btn btn-danger px-5" href="/>">Log Out</a>
				<a aria-label="Close" class="btn btn-primary px-5 text-white" data-bs-dismiss="modal">Stay Logged in</a>
			</div>
		</div>
	</div>
</div>

{% block javascript %}
<script>
	// after 10 minutes of inactivity, the user will be alerted that they are about to be logged out
	var idleTime = 0;
	$(document).ready(function () {
		var idleInterval = setInterval(timerIncrement, 600); // 1 minute
		$(this).mousemove(function (e) {idleTime = 0;});
		$(this).keypress(function (e) {idleTime = 0;});
	});

	function timerIncrement() {
		idleTime = idleTime + 1;
		console.log("User was idle for " + idleTime + " seconds");
		if (idleTime > 10) { // 10 minutes
			$('#myModal').modal('show');

			setInterval(function () {
				var progress = document.getElementById('custom-bar');
				if (progress.value < progress.max) {
					progress.value += 2;
				}
			}, 3000);

			// if the user chooses to stay logged in, the timer will reset
			$('#myModal').on('hidden.bs.modal', function () {
				idleTime = 0;
			})
		}
	}

</script>
{% endblock %}