general/accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"

urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("user/<str:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("new/user/", views.UserCreateView.as_view(), name="user_create"),
    path("user/<str:pk>/update/", views.UserUpdateView.as_view(), name="user_update"),
    path("user/<str:pk>/delete/", views.UserDeleteView.as_view(), name="user_delete"),
]

general/core/urls.py
from django.urls import path

from . import views


app_name = "core"

urlpatterns = [path("", views.HomeView.as_view(), name="home")]

general/employees/urls.py
from django.urls import path

from . import views


app_name = "employees"

urlpatterns = [
    
    path("department/", views.DepartmentListView.as_view(), name="department_list"),
    path("department/<str:pk>/", views.DepartmentDetailView.as_view(), name="department_detail"),
    path("new/department/", views.DepartmentCreateView.as_view(), name="department_create"),
    path("department/<str:pk>/update/", views.DepartmentUpdateView.as_view(), name="department_update"),
    path("department/<str:pk>/delete/", views.DepartmentDeleteView.as_view(), name="department_delete"),
   
]

general/gmanager/urls.py
from core.mixins import OpenView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.utils.translation import gettext_lazy as _


module_urls = i18n_patterns(
    path("", include("core.urls", namespace="core")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.backends.simple.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("employees/", include("employees.urls", namespace="employees")),
    prefix_default_language=False,
)

plugin_urls = [
    path("tinymce/", include("tinymce.urls")),
    path("translate/", include("rosetta.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml", OpenView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", OpenView.as_view(template_name="robots.txt", content_type="text/plain")),
    path(
        "OneSignalSDKWorker.js", OpenView.as_view(template_name="OneSignalSDKWorker.js", content_type="text/javascript")
    ),
]

urlpatterns = (
    module_urls
    + plugin_urls
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

PROJECT_NAME = settings.APP_SETTINGS.get("site_name")
admin.site.site_header = _("%(project_name)s Administration") % {"project_name": PROJECT_NAME}
admin.site.site_title = _("%(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}
admin.site.index_title = _("Welcome to %(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}

general/accounts/models.py
from core.functions import generate_fields
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy


class User(AbstractUser):
    

    def get_fields(self):
        return generate_fields(self)

    def get_absolute_url(self):
        return reverse_lazy("accounts:user_detail", kwargs={"pk": self.pk})

    @staticmethod
    def get_list_url():
        return reverse_lazy("accounts:user_list")

    def get_update_url(self):
        return reverse_lazy("accounts:user_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("accounts:user_delete", kwargs={"pk": self.pk})

    @property
    def fullname(self):
        return self.username

    def __str__(self):
        return self.username

    

general/accounts/views.py
from django.urls import reverse_lazy

from . import tables
from .models import User
from core import mixins


class UserListView(mixins.HybridListView):
    model = User
    table_class = tables.UserTable
    filterset_fields = ("is_active", "is_staff")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Users"
        context["can_add"] = True
        context["new_link"] = reverse_lazy("accounts:user_create")
        return context


class UserDetailView(mixins.HybridDetailView):
    model = User


class UserCreateView(mixins.HybridCreateView):
    model = User
    exclude = ("is_active", "date_joined", "user_permissions", "groups", "last_login", "is_superuser", "is_staff")
  

    def form_valid(self, form):
        form.instance.set_password(form.cleaned_data["password"])
        return super().form_valid(form)


class UserUpdateView(mixins.HybridUpdateView):
    model = User
    exclude = (
        "is_active",
        "password",
        "date_joined",
        "user_permissions",
        "groups",
        "last_login",
        "is_superuser",
        "is_staff",
    )



class UserDeleteView(mixins.HybridDeleteView):
    model = User

general/templates/app/sidebar/accounts.html
{% load static extras i18n %}
<!--app-sidebar-->
<div class="sticky">
    <aside class="app-sidebar">
        <div class="app-sidebar__logo">
            <a class="header-brand" href="/">
                <img src="{{app_settings.logo}}" class="header-brand-img desktop-lgo" alt="">
                <img src="{{app_settings.logo}}" class="header-brand-img dark-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img mobile-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img darkmobile-logo" alt="">
            </a>
        </div>
        <div class="app-sidebar3">
            <div class="main-menu">
                <div class="app-sidebar__user">
                    <div class="dropdown user-pro-body text-center">
                        <div class="user-pic">
                            {% if current_employee.photo %}
                            <img src="{{current_employee.photo.crop.74x74}}" alt=" "
                                class="avatar-xxl rounded-circle mb-1" />
                            {% else %}
                            <img src="{{default_user_avatar}}" alt=" " class="avatar-xxl rounded-circle mb-1" />
                            {% endif %}
                        </div>
                        <div class="user-info">
                            <h5 class="mb-2">{{request.user}}</h5>
                            <span class="app-sidebar__user-name text-sm">{{request.user.designation}}</span>
                        </div>
                    </div>
                </div>

                <div class="slide-left disabled" id="slide-left">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
                    </svg>
                </div>

                <ul class="side-menu py-0 module_info">
                    <li class="side-item side-item-category m-0 text-center">{{app_settings.site_name}}</li>
                </ul>

                <ul class="side-menu">

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'core:home' %}">
                            <i class="feather feather-airplay sidemenu_icon"></i>
                            <span class="side-menu__label">Dashboard</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'accounts:user_list' %}">
                            <i class="feather feather-users sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Users' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'clients:client_list' %}">
                            <i class="feather feather-user-check sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Clients' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'marketing:enquiry_list' %}">
                            <i class="feather feather-message-square sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Enquiries' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:employee_list' %}">
                            <i class="feather feather-users sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Employees' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:department_list' %}">
                            <i class="feather feather-grid sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Departments' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:designation_list' %}">
                            <i class="feather feather-award sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Designations' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:grade_list' %}">
                            <i class="feather feather-briefcase sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Grades' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'projects:project_list' %}">
                            <i class="feather feather-server sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Projects' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'tasks:task_list' %}">
                            <i class="feather feather-list sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Tasks' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'tasks:reminder_list' %}">
                            <i class="feather feather-alert-triangle sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Reminders' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'lms:course_list' %}">
                            <i class="feather feather-book sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Courses' %}<sup>New</sup></span>
                        </a>
                    </li>

                </ul>

                <div class="slide-right" id="slide-right">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                    </svg>
                </div>


            </div>
        </div>
    </aside>
</div>

general/templates/app/sidebar/hod.html
{% load static extras i18n %}
<!--app-sidebar-->
<div class="sticky">
    <aside class="app-sidebar">
        <div class="app-sidebar__logo">
            <a class="header-brand" href="/">
                <img src="{{app_settings.logo}}" class="header-brand-img desktop-lgo" alt="">
                <img src="{{app_settings.logo}}" class="header-brand-img dark-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img mobile-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img darkmobile-logo" alt="">
            </a>
        </div>
        <div class="app-sidebar3">
            <div class="main-menu">
                <div class="app-sidebar__user">
                    <div class="dropdown user-pro-body text-center">
                        <div class="user-pic">
                            {% if current_employee.photo %}
                            <img src="{{current_employee.photo.crop.74x74}}" alt=" "
                                class="avatar-xxl rounded-circle mb-1" />
                            {% else %}
                            <img src="{{default_user_avatar}}" alt=" " class="avatar-xxl rounded-circle mb-1" />
                            {% endif %}
                        </div>
                        <div class="user-info">
                            <h5 class="mb-2">{{request.user}}</h5>
                            <span class="app-sidebar__user-name text-sm">{{request.user.designation}}</span>
                        </div>
                    </div>
                </div>

                <div class="slide-left disabled" id="slide-left">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
                    </svg>
                </div>

                <ul class="side-menu py-0 module_info">
                    <li class="side-item side-item-category m-0 text-center">{{app_settings.site_name}}</li>
                </ul>

                <ul class="side-menu">

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'core:home' %}">
                            <i class="feather feather-airplay sidemenu_icon"></i>
                            <span class="side-menu__label">Dashboard</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'marketing:enquiry_list' %}">
                            <i class="feather feather-message-square sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Enquiries' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:employee_list' %}">
                            <i class="feather feather-users sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Employees' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:department_list' %}">
                            <i class="feather feather-grid sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Departments' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:designation_list' %}">
                            <i class="feather feather-award sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Designations' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:grade_list' %}">
                            <i class="feather feather-briefcase sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Grades' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'projects:project_list' %}">
                            <i class="feather feather-server sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Projects' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'tasks:task_list' %}">
                            <i class="feather feather-list sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Tasks' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'tasks:reminder_list' %}">
                            <i class="feather feather-alert-triangle sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Reminders' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'lms:course_list' %}">
                            <i class="feather feather-book sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Courses' %}<sup>New</sup></span>
                        </a>
                    </li>

                </ul>

                <div class="slide-right" id="slide-right">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                    </svg>
                </div>


            </div>
        </div>
    </aside>
</div>

general/templates/app/sidebar/hrm.html
{% load static extras i18n %}
<!--app-sidebar-->
<div class="sticky">
    <aside class="app-sidebar">
        <div class="app-sidebar__logo">
            <a class="header-brand" href="/">
                <img src="{{app_settings.logo}}" class="header-brand-img desktop-lgo" alt="">
                <img src="{{app_settings.logo}}" class="header-brand-img dark-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img mobile-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img darkmobile-logo" alt="">
            </a>
        </div>
        <div class="app-sidebar3">
            <div class="main-menu">
                <div class="app-sidebar__user">
                    <div class="dropdown user-pro-body text-center">
                        <div class="user-pic">
                            {% if current_employee.photo %}
                            <img src="{{current_employee.photo.crop.74x74}}" alt=" "
                                class="avatar-xxl rounded-circle mb-1" />
                            {% else %}
                            <img src="{{default_user_avatar}}" alt=" " class="avatar-xxl rounded-circle mb-1" />
                            {% endif %}
                        </div>
                        <div class="user-info">
                            <h5 class="mb-2">{{request.user}}</h5>
                            <span class="app-sidebar__user-name text-sm">{{request.user.designation}}</span>
                        </div>
                    </div>
                </div>

                <div class="slide-left disabled" id="slide-left">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
                    </svg>
                </div>

                <ul class="side-menu py-0 module_info">
                    <li class="side-item side-item-category m-0 text-center">{{app_settings.site_name}}</li>
                </ul>

                <ul class="side-menu">

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'core:home' %}">
                            <i class="feather feather-airplay sidemenu_icon"></i>
                            <span class="side-menu__label">Dashboard</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'accounts:user_list' %}">
                            <i class="feather feather-users sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Users' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'clients:client_list' %}">
                            <i class="feather feather-user-check sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Clients' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'marketing:enquiry_list' %}">
                            <i class="feather feather-message-square sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Enquiries' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:employee_list' %}">
                            <i class="feather feather-users sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Employees' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:department_list' %}">
                            <i class="feather feather-grid sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Departments' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:designation_list' %}">
                            <i class="feather feather-award sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Designations' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:grade_list' %}">
                            <i class="feather feather-briefcase sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Grades' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'projects:project_list' %}">
                            <i class="feather feather-server sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Projects' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'tasks:task_list' %}">
                            <i class="feather feather-list sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Tasks' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'tasks:reminder_list' %}">
                            <i class="feather feather-alert-triangle sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Reminders' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'lms:course_list' %}">
                            <i class="feather feather-book sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Courses' %}<sup>New</sup></span>
                        </a>
                    </li>

                </ul>

                <div class="slide-right" id="slide-right">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                    </svg>
                </div>


            </div>
        </div>
    </aside>
</div>

general/templates/app/sidebar/management.html
{% load static extras i18n %}
<!--app-sidebar-->
<div class="sticky">
    <aside class="app-sidebar">
        <div class="app-sidebar__logo">
            <a class="header-brand" href="/">
                <img src="{{app_settings.logo}}" class="header-brand-img desktop-lgo" alt="">
                <img src="{{app_settings.logo}}" class="header-brand-img dark-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img mobile-logo" alt="">
                <img src="{{app_settings.favicon}}" class="header-brand-img darkmobile-logo" alt="">
            </a>
        </div>
        <div class="app-sidebar3">
            <div class="main-menu">
                <div class="app-sidebar__user">
                    <div class="dropdown user-pro-body text-center">
                        <div class="user-pic">
                            {% if current_employee.photo %}
                            <img src="{{current_employee.photo.url}}" alt=" " width="74" height="74"
                                class="avatar-xxl rounded-circle mb-1" />
                            {% else %}
                            <img src="{{default_user_avatar}}" alt=" " class="avatar-xxl rounded-circle mb-1" />
                            {% endif %}
                        </div>
                        <div class="user-info">
                            <h5 class="mb-2">{{request.user}}</h5>
                            <span class="app-sidebar__user-name text-sm">{{request.user.designation}}</span>
                        </div>
                    </div>
                </div>
                <div class="slide-left disabled" id="slide-left">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
                    </svg>
                </div>

                <ul class="side-menu py-0 module_info">
                    <li class="side-item side-item-category m-0 text-center">{{app_settings.site_name}}</li>
                </ul>

                <ul class="side-menu">

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'core:home' %}">
                            <i class="feather feather-airplay sidemenu_icon"></i>
                            <span class="side-menu__label">Dashboard</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'accounts:user_list' %}">
                            <i class="feather feather-users sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Users' %}</span>
                        </a>
                    </li>

                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{% url 'employees:department_list' %}">
                            <i class="feather feather-grid sidemenu_icon"></i>
                            <span class="side-menu__label">{% translate 'Departments' %}</span>
                        </a>
                    </li>

                </ul>

                <div class="slide-right" id="slide-right">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                    </svg>
                </div>
            </div>
        </div>
    </aside>
</div>